### ISSUE TITLE
ビルドpre-build失敗のWARNINGが出る

### ISSUE THREAD

**Issue by ngwork0301** [ngwork0301/mkdocs-blog#34]
## 現象
`mkdocs build`で以下のWARNINGがでる
[Github actions:Build static pages and deploy:runs/2679326550](https://github.com/ngwork0301/mkdocs-blog/runs/2679326550?check_suite_focus=true#step:8:20)
```
 WARNING -  Failed to pre-build search index. Error: b'/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/mkdocs/contrib/search/lunr-language/lunr.ja.js:86\n    var segmenter = new lunr.TinySegmenter(); // \xe3\x82\xa4\xe3\x83\xb3\xe3\x82\xb9\xe3\x82\xbf\xe3\x83\xb3\xe3\x82\xb9\xe7\x94\x9f\xe6\x88\x90\n                    ^\n\nTypeError: lunr.TinySegmenter is not a constructor\n    at /opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/mkdocs/contrib/search/lunr-language/lunr.ja.js:86:21\n    at Socket.<anonymous> (/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/mkdocs/contrib/search/prebuild-index.js:27:55)\n    at Socket.emit (events.js:388:22)\n    at endReadableNT (internal/streams/readable.js:1336:12)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21)\n'
```

**Comment by ngwork0301** [comment]
2803d51bb13347c86cec440477cff9caf9338696 でMkDocsのベースバージョンを更新して消えたっぽい
クローズする。
