### ISSUE TITLE
mdx-unimojiのインストールに失敗してデプロイできない。

### ISSUE THREAD

**Issue by ngwork0301** [ngwork0301/mkdocs-blog#65]
## 現象
GitHub ActionsでのBuild and Deployが失敗する。
具体的には以下のエラーが出力され、pipでのmdx-unimojiのインストールに失敗する。
``` python
Collecting mdx-unimoji==1.0
  Downloading mdx_unimoji-1.0.tar.gz (3.9 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      WARNING: The wheel package is not available.
      WARNING: The wheel package is not available.
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-4fp8nltr/mdx-unimoji_9c6491620ed049[76](https://github.com/ngwork0301/mkdocs-blog/runs/6446068794?check_suite_focus=true#step:6:76)b81a7f6f[78](https://github.com/ngwork0301/mkdocs-blog/runs/6446068794?check_suite_focus=true#step:6:78)41f316/setup.py", line 10, in <module>
          setup(
        File "/opt/hostedtoolcache/Python/3.10.1/x64/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/opt/hostedtoolcache/Python/3.10.1/x64/lib/python3.10/distutils/core.py", line 108, in setup
          _setup_distribution = dist = klass(attrs)
        File "/opt/hostedtoolcache/Python/3.10.1/x64/lib/python3.10/site-packages/setuptools/dist.py", line 453, in __init__
          _Distribution.__init__(
        File "/opt/hostedtoolcache/Python/3.10.1/x64/lib/python3.10/distutils/dist.py", line 292, in __init__
          self.finalize_options()
        File "/opt/hostedtoolcache/Python/3.10.1/x64/lib/python3.10/site-packages/setuptools/dist.py", line 831, in finalize_options
          ep(self)
        File "/opt/hostedtoolcache/Python/3.10.1/x64/lib/python3.10/site-packages/setuptools/dist.py", line 852, in _finalize_setup_keywords
          ep.load()(self, ep.name, value)
        File "/tmp/pip-install-4fp8nltr/mdx-unimoji_9c6491620ed04976b[81](https://github.com/ngwork0301/mkdocs-blog/runs/6446068794?check_suite_focus=true#step:6:81)a7f6f7[84](https://github.com/ngwork0301/mkdocs-blog/runs/6446068794?check_suite_focus=true#step:6:84)1f316/.eggs/setuptools_markdown-0.4.1-py3.10.egg/setuptools_markdown.py", line 43, in long_description_markdown_filename
          output = pypandoc.convert(markdown_filename, 'rst', format='md')
      AttributeError: module 'pypandoc' has no attribute 'convert'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```

## 備考
2022/5/11 に [pypandoc 1.8のリリース](https://pypi.org/project/pypandoc/1.8/)があった様子。これ以降、`pypandoc.convert()`は使えなくなり、代わりに`pypandoc.convert_file()`または、`pypandoc.convert_text()`を使う仕様に変わったように見える。

**Comment by ngwork0301** [comment]
## 原因
上記のとおり、[pypandoc 1.8](https://pypi.org/project/pypandoc/1.8/) の仕様変更によるものだった様子。  

## 対処
以下の修正で、明示的に仕様変更される直前の1.7.5を使用するように指定して対処。
https://github.com/ngwork0301/mkdocs-blog/commit/0557b04379bab9eb1ae34ca5200779b72020970c
